#!/usr/bin/env python
from Queue import Queue
from threading import Thread
from pprint import pprint
import sys

from application.server.web_service import app_server
#from watchdogs.nethogs import NethogsWatchdog

if(len(sys.argv)==2 and sys.argv[1]=='server'):
    app_server()
else :
    server=Thread(
        target=app_server
    )

    server.daemon=True
    server.start()
    from application.view.window import window

    window('hogwatch','http://127.0.0.1:8010/index.html')