#!/usr/bin/env python
from Queue import Queue
from threading import Thread
from pprint import pprint
import sys

from application.server.web_service import app_server
#from watchdogs.nethogs import NethogsWatchdog

if(len(sys.argv)>=2 and sys.argv[1]=='server'):
    if(sys.argv[2]):
        app_server(port=int(sys.argv[2]))
    else:
        app_server()
else :
    server=Thread(
        target=app_server
    )

    server.daemon=True
    server.start()
    from application.view.window import window

    window('hogwatch','http://127.0.0.1:8010/index.html')